In [4]:
import numpy as np 
import torch
a=np.ones([2,3])
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
b=torch.from_numpy(a)
b

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [7]:
c=torch.Tensor(a)
c

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
a[0,1]=100
b

tensor([[  1., 100.,   1.],
        [  1.,   1.,   1.]], dtype=torch.float64)

In [9]:
c=b.numpy()
c

array([[  1., 100.,   1.],
       [  1.,   1.,   1.]])