In [6]:
import torch
a=torch.arange(0,6)
a

tensor([0, 1, 2, 3, 4, 5])

In [7]:
b=a.view(2,3)
b

tensor([[0, 1, 2],
        [3, 4, 5]])

In [8]:
a.storage()

 0
 1
 2
 3
 4
 5
[torch.LongStorage of size 6]

In [10]:
b.storage()

 0
 1
 2
 3
 4
 5
[torch.LongStorage of size 6]

In [11]:
a[0]=10
b

tensor([[10,  1,  2],
        [ 3,  4,  5]])

In [14]:
c=a[2:]
c

tensor([2, 3, 4, 5])

In [15]:
c.storage()

 10
 1
 2
 3
 4
 5
[torch.LongStorage of size 6]

In [18]:
a.data_ptr(),c.data_ptr()

(93874598017024, 93874598017040)

In [19]:
c[0]=-1
c

tensor([-1,  3,  4,  5])

In [20]:
a

tensor([10,  1, -1,  3,  4,  5])

In [23]:
a.storage_offset(),b.storage_offset(),c.storage_offset(),

(0, 0, 2)

In [26]:
e=b[::2,::2]
b,e

(tensor([[10,  1, -1],
         [ 3,  4,  5]]),
 tensor([[10, -1]]))

In [27]:
b.stride(),e.stride()

((3, 1), (6, 2))