In [1]:
import torch
a=torch.Tensor(2,3)
a

tensor([[2.4755e-12, 4.0728e-11, 1.1704e-19],
        [1.3563e-19, 1.3563e-19, 4.5071e+16]])

In [2]:
b=torch.Tensor([[1,2,3],[4,5,6]])
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [3]:
c=b.tolist()
c

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]

In [4]:
b.size()

torch.Size([2, 3])

In [5]:
b.numel()

6

In [6]:
d=torch.Tensor(b.size())
d

tensor([[-3.2550e-18,  4.5635e-41,  8.9503e+26],
        [ 3.0831e-41,  4.4842e-44,  0.0000e+00]])

In [7]:
e=torch.Tensor([(2,3),(4,5)])
e

tensor([[2., 3.],
        [4., 5.]])

In [8]:
a=torch.arange(0,6)
a

tensor([0, 1, 2, 3, 4, 5])

In [9]:
a.view(2,3)

tensor([[0, 1, 2],
        [3, 4, 5]])

In [10]:
b=a.view(-1,3)
b

tensor([[0, 1, 2],
        [3, 4, 5]])

In [11]:
b.unsqueeze(-2)

tensor([[[0, 1, 2]],

        [[3, 4, 5]]])

In [12]:
c=b.view(1,1,1,2,3)
c

tensor([[[[[0, 1, 2],
           [3, 4, 5]]]]])

In [13]:
c.squeeze()

tensor([[0, 1, 2],
        [3, 4, 5]])

In [14]:
a[0]=100
b

tensor([[100,   1,   2],
        [  3,   4,   5]])

In [15]:
c

tensor([[[[[100,   1,   2],
           [  3,   4,   5]]]]])

In [16]:
b.resize_(1,3)

tensor([[100,   1,   2]])

In [17]:
b.resize_(3,3)

tensor([[100,   1,   2],
        [  3,   4,   5],
        [  0,   0,   0]])

In [18]:
a=torch.randn(3,4)
a

tensor([[-2.1424, -0.7432, -1.7151,  1.0911],
        [-0.2257,  0.9828,  0.4808,  0.5820],
        [-1.3587,  0.3368,  1.5123,  0.1254]])

In [19]:
a[0]

tensor([-2.1424, -0.7432, -1.7151,  1.0911])

In [20]:
a[:,0]

tensor([-2.1424, -0.2257, -1.3587])

In [21]:
a[0][0]

tensor(-2.1424)

In [22]:
a[0][-1]

tensor(1.0911)

In [23]:
a[:3]

tensor([[-2.1424, -0.7432, -1.7151,  1.0911],
        [-0.2257,  0.9828,  0.4808,  0.5820],
        [-1.3587,  0.3368,  1.5123,  0.1254]])

In [24]:
a[:3,2:3]

tensor([[-1.7151],
        [ 0.4808],
        [ 1.5123]])

In [25]:
a>1

tensor([[False, False, False,  True],
        [False, False, False, False],
        [False, False,  True, False]])

In [26]:
a[a>1]

tensor([1.0911, 1.5123])

In [40]:
a=torch.arange(0,16).view(4,4)
index=torch.LongTensor([[0,1,2,3]])
a

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [41]:
b=a.gather(0,index)
b


tensor([[ 0,  5, 10, 15]])

In [46]:
index=torch.LongTensor([[3,2,1,0]]).t()
b=a.gather(1,index)
b

tensor([[ 3],
        [ 6],
        [ 9],
        [12]])

In [47]:
index=torch.LongTensor([[3,2,1,0]])
b=a.gather(0,index)
b

tensor([[12,  9,  6,  3]])

In [49]:
index=torch.LongTensor([[0,1,2,3],[3,2,1,0]]).t()
b=a.gather(1,index)
b

tensor([[ 0,  3],
        [ 5,  6],
        [10,  9],
        [15, 12]])

In [73]:
a=torch.Tensor([2,3])
a

tensor([2., 3.])

In [74]:
b=a.int()
b

tensor([2, 3], dtype=torch.int32)

In [77]:
c=a.type_as(b)
c

tensor([2, 3], dtype=torch.int32)

In [78]:
d=a.new(2,3)
d

tensor([[9.1587e+26, 3.0831e-41, 9.1068e+26],
        [3.0831e-41, 4.4842e-44, 0.0000e+00]])

In [79]:
a.new??

In [87]:
b=torch.ones(2,3)
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [90]:
c=b.sum(dim=0,keepdim=True)

In [91]:
c.size()

torch.Size([1, 3])

In [93]:
a=torch.arange(0,6).view(2,3)
a

tensor([[0, 1, 2],
        [3, 4, 5]])

In [94]:
b=a.cumsum(dim=1)
b

tensor([[ 0,  1,  3],
        [ 3,  7, 12]])

In [96]:
a=torch.ones(3,1)
a

tensor([[1.],
        [1.],
        [1.]])

In [97]:
a.shape

torch.Size([3, 1])

In [99]:
b=a.t()
b

tensor([[1., 1., 1.]])

In [102]:
b.is_contiguous()

True