In [1]:
import torch
from torch.autograd import Variable
x=torch.ones(1)
b=torch.rand(1,requires_grad=True)
w=torch.rand(1,requires_grad=True)
y=w*x
z=y+b

In [2]:
x.is_leaf,y.is_leaf

(True, False)

In [3]:
y,z

(tensor([0.7020], grad_fn=<MulBackward0>),
 tensor([0.9657], grad_fn=<AddBackward0>))

In [4]:
z.grad_fn.next_functions

((<MulBackward0 at 0x7fdd57230910>, 0),
 (<AccumulateGrad at 0x7fdd57230a90>, 0))

In [10]:
def abs(x):
    if x.data[0]>0 :return x
    else :return -x
x=Variable(-1*torch.ones(1),requires_grad=True)
y=abs(x)
x,y

(tensor([-1.], requires_grad=True), tensor([1.], grad_fn=<NegBackward>))

In [11]:
y.backward()

In [12]:
print(x.grad)

tensor([-1.])


In [22]:
def f(x):
    result=1
    for ii in x:
        if ii>0:result=ii*result
    return result
x=Variable(torch.arange(-2,4,1.0),requires_grad=True)
y=f(x)
y.backward()
x.grad,y


(tensor([0., 0., 0., 6., 3., 2.]), tensor(6., grad_fn=<MulBackward0>))

In [24]:
x=Variable(torch.ones(1))
w=Variable(torch.rand(1),requires_grad=True)
y=x*w
x.requires_grad,y.requires_grad,z.requires_grad,

(False, True, True)

In [25]:
x=Variable(torch.ones(3),requires_grad=True)
w=Variable(torch.rand(3),requires_grad=True)
y=x*w
z=y.sum()
print(z)
x.requires_grad,w.requires_grad,y.requires_grad,

tensor(1.9875, grad_fn=<SumBackward0>)


(True, True, True)

In [26]:
z.backward()
x.grad,w.grad,y.grad

(tensor([0.4415, 0.9311, 0.6149]), tensor([1., 1., 1.]), None)

In [27]:
x=Variable(torch.ones(3),requires_grad=True)
w=Variable(torch.rand(3),requires_grad=True)
y=x*w
z=y.sum()
torch.autograd.grad(z,y)

(tensor([1., 1., 1.]),)

In [28]:
def variable_hook(grad):
    print('y的梯度： \r\n',grad)
x=Variable(torch.ones(3),requires_grad=True)
w=Variable(torch.rand(3),requires_grad=True)
y=x*w
hook_handle=y.register_hook(variable_hook)
z=y.sum()
z.backward()
hook_handle.remove()


y的梯度： 
 tensor([1., 1., 1.])


In [36]:
x=Variable(torch.arange(0,3,1.0),requires_grad=True)
y=x**2+2*x
z=y.sum()
z.backward()
x,y,z,x.grad,y.grad

(tensor([0., 1., 2.], requires_grad=True),
 tensor([0., 3., 8.], grad_fn=<AddBackward0>),
 tensor(11., grad_fn=<SumBackward0>),
 tensor([2., 4., 6.]),
 None)

In [38]:
x=Variable(torch.arange(0,3,1.0),requires_grad=True)
y=x**2+2*x
z=y.sum()
y.backward(torch.ones(3))
x,y,z,x.grad,y.grad

(tensor([0., 1., 2.], requires_grad=True),
 tensor([0., 3., 8.], grad_fn=<AddBackward0>),
 tensor(11., grad_fn=<SumBackward0>),
 tensor([2., 4., 6.]),
 None)