In [1]:
import torch
#Autograd求导与手动求导区别
def f(x):
    y=x**2*torch.exp(x)
    return y
def gradf(x):
    '''手动求导'''
    dx=2*x*torch.exp(x)+x**2*torch.exp(x)
    return dx


In [2]:
x=torch.randn(3,4,requires_grad=True)
y=f(x)
y

tensor([[8.7301e-03, 1.0667e-02, 2.5545e+00, 5.9792e+00],
        [9.0186e+00, 2.5935e-01, 3.1000e+00, 4.0671e-01],
        [5.3601e-01, 2.4638e-01, 5.4336e+01, 1.4956e+00]],
       grad_fn=<MulBackward0>)

In [3]:
y.backward(torch.ones(y.size()))

In [4]:
x.grad

tensor([[-1.6919e-01,  2.2764e-01,  7.7709e+00,  1.5280e+01],
        [ 2.1436e+01,  1.5122e+00,  9.0363e+00, -3.2477e-01],
        [-5.7038e-02,  1.4621e+00,  1.0126e+02,  5.1700e+00]])

In [5]:
gradf(x)

tensor([[-1.6919e-01,  2.2764e-01,  7.7709e+00,  1.5280e+01],
        [ 2.1436e+01,  1.5122e+00,  9.0363e+00, -3.2477e-01],
        [-5.7038e-02,  1.4621e+00,  1.0126e+02,  5.1700e+00]],
       grad_fn=<AddBackward0>)