In [7]:
import torch as t
from torch.autograd import Variable
x=Variable(t.ones(2,2),requires_grad=True)
x


tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [8]:
y=t.ones(2,2,requires_grad=True)
y

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [9]:
y=x.sum()
y

tensor(4., grad_fn=<SumBackward0>)

In [10]:
y.grad_fn

In [11]:
y.backward()

In [14]:
x.grad

tensor([[1., 1.],
        [1., 1.]])

In [16]:
y.backward()
x.grad

tensor([[2., 2.],
        [2., 2.]])

In [17]:
x.grad.data.zero_()

tensor([[0., 0.],
        [0., 0.]])

In [18]:
y.backward()
x.grad

tensor([[1., 1.],
        [1., 1.]])

In [20]:
x=t.ones(2,2)
x

tensor([[1., 1.],
        [1., 1.]])

In [21]:
x.data

tensor([[1., 1.],
        [1., 1.]])